### PR TITLE
fix: actionlint errors on non-existing context in some events

### PR DESCRIPTION
**Pull request by guidojw**
### Summary

Fixes the actionlint errors from #576 by ignoring the error message.

### CODE REVIEW

**Review by wilco375 — APPROVED** [review]

**Comment by wilco375** [comment]
The linter now falls with `undefined variable "env". available variables are "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy" [expression]` 😅

**Comment by guidojw** [comment]
> The linter now falls with `undefined variable "env". available variables are "github", "inputs", "job", "matrix", "needs", "runner", "secrets", "steps", "strategy" [expression]` 😅

Yeah apparently downloading the script from v1.6.15 gets you actionlint v1.6.14 😅, I will take another look later.

**Comment by guidojw** [comment]
@wilco375 ignored the error message for now, I'll come back to pinning actionlint's version later.

**Review by wilco375 — APPROVED** [review]

**Comment by guidojw** [comment]
actionlint is now pinned, will configure Renovate config in https://github.com/csvalpha/.github soon to have it automatically update the version.

**Pull request merged**
