### PR TITLE
refactor(*): rename alpha-amber with amber-ui

### PR DESCRIPTION
**Pull request by guidojw**
### Summary

Replaces all occurrences of `alpha-amber` with `amber-ui` for more consistency.

### Other information

- [ ] @DrumsnChocolate when this is merged, replace https://sentry.io/settings/csvalpha/integrations/github/ -> Configurations -> Configure -> Code Mappings and then the occurrence of `alpha-amber` with `amber-ui` (I do not have permissions to do this anymore).

### CODE REVIEW

**Review by DrumsnChocolate — APPROVED** [review]
Looks good. Note: there is one occurrence that is not refactored by this, in `.yarn-state.yml` :wink: (or yarn error logs)
but that's gone as soon as one runs `yarn install`

**Comment by guidojw** [comment]
I do not have a `.yarn-state.yml`, maybe this is a local file?

**Comment by guidojw** [comment]
@DrumsnChocolate this is merging soon, can you do the check from the description?

**Comment by guidojw** [comment]
I cannot 😂, can you send a screenshot of the code mappings? 
If for `amber-ui` repository, `amber-ui/` now maps to `app/`, it should be correct.

**Comment by DrumsnChocolate** [comment]
image

**Pull request merged**
