### PR TITLE
refactor(models): remove usage of deprecated Model.reopen

### LINKED ISSUE #432: Remove usage of deprecated Model.reopen
https://emberjs.github.io/rfcs/0738-ember-data-deprecate-model-reopen.html

### PR DESCRIPTION
**Pull request by guidojw**
### Summary
Resolves #432.

I also converted the response model to a native class, it's promise hell but seems to work.

### CODE REVIEW

**Review by wilco375 — APPROVED** [review]

**Comment by guidojw** [comment]
This in fact doesn't work, response answers do not show up in the responses-table on activities.
Will fix and then rerequest a review.

**Comment by guidojw** [comment]
**Now** it should be working, but please double check if it works by for example testing activity inschrijflijsten.

**Comment by wilco375** [comment]
@guidojw Something's going wrong with the multiple choice closed answer. When I select multiple answers only one of them is shown in the activity list:
image

**Comment by wilco375** [comment]
Other than that everything seems to be working

**Comment by guidojw** [comment]
Should be fixed in bc81ab24a841c154779d2d803e2a521bf437074a

**Review by wilco375 — APPROVED** [review]

**Pull request merged**
