### PR TITLE
feat: show numeric keyboard for OTP code

### PR DESCRIPTION
**Pull request by guidojw**
### Summary
Adds the pattern attribute to the auth code input so that iOS devices will show a numeric keyboard instead (Android does not do this).

### CODE REVIEW

**Comment by wilco375** [comment]
Can't we just make it a type="number" field?

**Comment by guidojw** [comment]
No, that won't force a numeric keyboard on iOS and will show increment/decrement buttons which do not make much sense for this field

**Comment by wilco375** [comment]
You should be able to add `inputmode="numeric"` for Android. Can you also add that?
https://css-tricks.com/finger-friendly-numerical-inputs-with-inputmode/#aa-a-better-solution-inputmode

**Comment by guidojw** [comment]
That seems useful too, added 👍🏿

**Review by wilco375 — APPROVED** [review]

**Pull request merged**
