### PR TITLE
Added docker compose file for development

### PR DESCRIPTION
**Pull request by Ellen-Wittingen**
Added docker compose file so the UI can be run as a docker container on a developers computer

TODO: add instructions to README.md

### CODE REVIEW

**Review by DrumsnChocolate — APPROVED** [review]
Lgtm. Haven't tested this, but I'm pretty busy so it's probably faster to have the onboarders test it

**Comment by DrumsnChocolate** [comment]
(approving in advance :D)

**Comment by lodewiges** [comment]
this is not needed anymore with the introduction of the development environment

**Comment by lodewiges** [comment]
is this still needed with the introduction of the development Environment

**Comment by DrumsnChocolate** [comment]
I don't know, I have not yet looked at the repo you're referring to

**Comment by Ellen-Wittingen** [comment]
Probs not needed anymore if the other one works. Otherwise you have two images that can do the same thing

**Comment by lodewiges** [comment]
the other one mostly works with some workarounds I think these should not be that _hard_ to implement

**Pull request closed without merging**
